-- ER Permission Report — Supabase/PostgreSQL schema
-- Safe to run more than once in the Supabase SQL Editor.

create table if not exists public.users (
  id text primary key,
  discord_id text not null unique,
  username text not null,
  display_name text not null,
  avatar_url text,
  staff_rank text not null,
  created_at bigint not null,
  last_login_at bigint not null,
  last_sync_at bigint not null
);

create table if not exists public.permission_reports (
  id bigint generated by default as identity primary key,
  public_id text not null unique,
  created_by_user_id text not null references public.users(id),
  permission_type text not null,
  target_player_name text,
  target_player_id text not null,
  target_discord_id text,
  reason text not null,
  incident_at bigint,
  status text not null default 'Pending',
  no_evidence integer not null default 0,
  priority text not null default 'Normal',
  reviewer_user_id text references public.users(id),
  review_started_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  archived_at bigint
);

create table if not exists public.evidence (
  id text primary key,
  report_id bigint not null references public.permission_reports(id),
  kind text not null,
  object_key text,
  external_url text,
  file_name text,
  mime_type text,
  size_bytes bigint,
  uploaded_by_user_id text not null references public.users(id),
  created_at bigint not null
);

create table if not exists public.notifications (
  id text primary key,
  user_id text not null references public.users(id),
  report_id bigint references public.permission_reports(id),
  type text not null,
  message text not null,
  read_at bigint,
  created_at bigint not null
);

create table if not exists public.audit_logs (
  id text primary key,
  report_id bigint references public.permission_reports(id),
  actor_user_id text references public.users(id),
  action text not null,
  old_value text,
  new_value text,
  ip_hash text,
  created_at bigint not null
);

create table if not exists public.permission_log_imports (
  id text primary key,
  public_id text not null unique,
  filename text not null,
  file_type text not null,
  file_size bigint not null,
  uploaded_by_user_id text not null references public.users(id),
  column_mapping_json text not null,
  total_rows integer not null,
  valid_rows integer not null,
  invalid_rows integer not null,
  duplicate_rows integer not null,
  matched_rows integer not null,
  unmatched_rows integer not null,
  review_required_rows integer not null,
  status text not null default 'Completed',
  created_at bigint not null,
  completed_at bigint
);

create table if not exists public.permission_usage_logs (
  id text primary key,
  import_batch_id text not null references public.permission_log_imports(id),
  source_row_number integer not null,
  staff_discord_id text,
  staff_user_id text references public.users(id),
  permission_type text,
  target_player_id text,
  target_discord_id text,
  action_at bigint,
  server_name text,
  raw_log_id text,
  raw_metadata_json text not null,
  validation_error text,
  match_status text not null,
  matched_permission_report_id bigint references public.permission_reports(id),
  time_difference_seconds integer,
  match_explanation_json text,
  review_status text not null default 'Not Reviewed',
  reviewed_by_user_id text references public.users(id),
  reviewed_at bigint,
  review_note text,
  created_at bigint not null,
  unique(import_batch_id, source_row_number)
);

create index if not exists idx_permission_reports_owner_created on public.permission_reports(created_by_user_id, created_at);
create index if not exists idx_permission_reports_status_created on public.permission_reports(status, created_at);
create index if not exists idx_evidence_report_id on public.evidence(report_id);
create index if not exists idx_audit_logs_report_created on public.audit_logs(report_id, created_at);
create index if not exists idx_permission_usage_import_status on public.permission_usage_logs(import_batch_id, match_status);
create index if not exists idx_permission_usage_staff_action on public.permission_usage_logs(staff_discord_id, action_at);
create index if not exists idx_permission_usage_matched_report on public.permission_usage_logs(matched_permission_report_id);

alter table public.users enable row level security;
alter table public.permission_reports enable row level security;
alter table public.evidence enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;
alter table public.permission_log_imports enable row level security;
alter table public.permission_usage_logs enable row level security;

insert into storage.buckets (id, name, public, file_size_limit)
values ('er-evidence', 'er-evidence', false, 104857600)
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit;
