"use client";

import { useEffect, useState } from "react";

type Usage={id:string;match_status:string;staff_name:string;staff_rank:string;staff_discord_id:string|null;permission_type:string|null;target_player_id:string|null;action_at:number|null;raw_log_id:string|null;import_public_id:string;filename:string;matched_report_public_id:string|null};
type Candidate={id:number;public_id:string;permission_type:string;target_player_id:string;incident_at:number};

const displayTime=(seconds:number|null)=>seconds?new Intl.DateTimeFormat("en-GB",{dateStyle:"long",timeStyle:"medium",timeZone:"Asia/Jerusalem"}).format(new Date(seconds*1000)):"Unknown";

export function ReconciliationUsageLive(){
  const [usage,setUsage]=useState<Usage|null>(null),[candidates,setCandidates]=useState<Candidate[]>([]),[note,setNote]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const id=typeof window!=="undefined"?window.location.pathname.split("/").filter(Boolean).at(-1)||"":"";
  const load=async()=>{const response=await fetch(`/api/management/reconciliation/${encodeURIComponent(id)}`);const data=await response.json() as {usage?:Usage;candidates?:Candidate[];error?:string};if(!response.ok)throw new Error(data.error||"Unable to load this item.");setUsage(data.usage||null);setCandidates(data.candidates||[])};
  useEffect(()=>{load().catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load this item."))},[id]);
  const act=async(action:string,reportId?:number)=>{setBusy(true);setError("");try{const response=await fetch(`/api/management/reconciliation/${encodeURIComponent(id)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,reportId,reason:note})});const data=await response.json() as {status?:string;error?:string};if(!response.ok)throw new Error(data.error||"Unable to update this reconciliation item.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Action failed.")}finally{setBusy(false)}};
  if(!usage)return <div className="page narrow">{error?<div className="toast error">! {error}</div>:<div className="panel">Loading reconciliation item…</div>}</div>;
  return <div className="page narrow"><div className="crumb"><a href="/management/reconciliation">Permission Reconciliation</a><span>›</span>{usage.id}</div><div className="page-head"><div><p>PERMISSION USAGE REVIEW</p><h1>{usage.permission_type||"Invalid permission"} · Player ID {usage.target_player_id||"—"}</h1><span>Imported from {usage.import_public_id} · {usage.filename}</span></div><span className={`badge badge-${usage.match_status.toLowerCase().replaceAll("_","-")}`}>{usage.match_status.replaceAll("_"," ")}</span></div>{error&&<div className="toast error">! {error}</div>}<div className="usage-detail"><section className="panel"><div className="section-title"><div><span>Server Permission Usage</span><small>Original imported action, sanitized for display</small></div></div><div className="info-grid"><div><span>Staff</span><b>{usage.staff_name}</b><small>{usage.staff_rank}</small></div><div><span>Discord ID</span><b>{usage.staff_discord_id||"Unknown"}</b><small>Authoritative identity</small></div><div><span>Permission</span><b>{usage.permission_type||"Unsupported"}</b></div><div><span>Target</span><b>Player ID {usage.target_player_id||"—"}</b></div><div><span>Permission Used At</span><b>{displayTime(usage.action_at)}</b><small>Asia/Jerusalem</small></div><div><span>Raw Log ID</span><b>{usage.raw_log_id||"Not supplied"}</b></div></div></section><section className="panel"><div className="section-title"><div><span>Possible Permission Reports</span><small>Ranked by the closest incident time for the same Discord ID</small></div></div>{candidates.map(candidate=><div className="candidate" key={candidate.id}><div><a href={`/permission-reports/${candidate.public_id}`}>{candidate.public_id}</a><p>{candidate.permission_type} · Player ID {candidate.target_player_id} · {displayTime(candidate.incident_at)}</p></div><button disabled={busy} onClick={()=>act("link",candidate.id)}>Link Report</button></div>)}{!candidates.length&&<p>No Permission Reports from this Discord ID were found.</p>}</section><section className="panel"><div className="section-title"><div><span>Management actions</span><small>Every decision is recorded in Audit Logs</small></div></div><label>Review note<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Required for exceptions and recommended for review decisions…"/></label><div className="usage-actions"><button disabled={busy} onClick={()=>act("keep_unreported")}>Keep Unreported</button><button disabled={busy} onClick={()=>act("duplicate")}>Mark as Duplicate</button><button disabled={busy||!note.trim()} onClick={()=>act("exception")}>Mark as Exception</button><button disabled={busy} className="primary" onClick={()=>act("rerun")}>{busy?"Working…":"↻ Re-run Matching"}</button></div></section></div></div>;
}
