"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useState } from "react";

export function ReconciliationUsageLive(){
  const [status,setStatus]=useState("UNREPORTED"),[note,setNote]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const act=async(action:string,reportId?:number)=>{setBusy(true);setError("");try{const response=await fetch("/api/management/reconciliation/USE-8494",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,reportId,reason:note})});const data=await response.json() as {status?:string;error?:string};if(!response.ok)throw new Error(data.error||"Unable to update this reconciliation item.");setStatus(data.status||status);}catch(reason){setError(reason instanceof Error?reason.message:"Action failed.");}finally{setBusy(false)}};
  return <div className="page narrow"><div className="crumb"><a href="/management/reconciliation">Permission Reconciliation</a><span>›</span>USE-8494</div><div className="page-head"><div><p>UNREPORTED PERMISSION USAGE</p><h1>Bring · Player ID 92</h1><span>Imported from ER-IMPORT-0021 · permissions-2026-08-13.xlsx</span></div><span className={`badge badge-${status.toLowerCase().replaceAll("_","-")}`}>{status.replaceAll("_"," ")}</span></div>{error&&<div className="toast error">! {error}</div>}<div className="usage-detail"><section className="panel"><div className="section-title"><div><span>Server Permission Usage</span><small>Original imported action, sanitized for display</small></div></div><div className="info-grid"><div><span>Staff</span><b>Daniel Mercer</b><small>Senior Admin</small></div><div><span>Discord ID</span><b>482930104829104128</b><small>Authoritative identity</small></div><div><span>Permission</span><b>Bring</b></div><div><span>Target</span><b>Player ID 92</b></div><div><span>Permission Used At</span><b>13 August 2026 · 12:03:18</b><small>Asia/Jerusalem</small></div><div><span>Raw Log ID</span><b>fivem-6fd18c</b></div></div></section><section className="panel no-match"><i>!</i><div><h3>No matching Permission Report found</h3><p>Discord ID, permission, target ID and ±10 minutes were checked. The 15-minute grace period has expired.</p></div></section><section className="panel"><div className="section-title"><div><span>Management actions</span><small>Every decision is recorded in Audit Logs</small></div></div><div className="candidate"><div><span>Possible match</span><a href="/permission-reports/ER-PR-1079">ER-PR-1079</a><p>Bring · Player ID 92 · 15m 18s difference</p></div><button disabled={busy} onClick={()=>act("link",1079)}>Link Permission Report</button></div><label>Review note<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Required for exceptions and confirmation decisions…"/></label><div className="usage-actions"><button disabled={busy} onClick={()=>act("keep_unreported")}>Keep Unreported</button><button disabled={busy} onClick={()=>act("duplicate")}>Mark as Duplicate</button><button disabled={busy||!note.trim()} onClick={()=>act("exception")}>Mark as Exception</button><button disabled={busy} className="primary" onClick={()=>act("rerun")}>{busy?"Working…":"↻ Re-run Matching"}</button></div></section></div></div>
}
