import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { normalizePermission, reconcilePermissionUsage, type PermissionReportCandidate } from "../../../../../../../lib/reconciliation";
import { requireHigherStaffManagement } from "../../../../../../../lib/server-auth";

type Usage={id:string;source_row_number:number;staff_discord_id:string|null;permission_type:string|null;target_player_id:string|null;target_discord_id:string|null;action_at:number|null;raw_log_id:string|null;validation_error:string|null};
type Report={id:number;public_id:string;discord_id:string;permission_type:string;target_player_id:string;incident_at:number};

export async function POST(_:Request,{params}:{params:Promise<{id:string}>}){
  const access=await requireHigherStaffManagement();if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const {id}=await params;
  const usages=(await env.DB.prepare(`SELECT id,source_row_number,staff_discord_id,permission_type,target_player_id,target_discord_id,action_at,raw_log_id,validation_error FROM permission_usage_logs WHERE import_batch_id=? AND match_status IN ('AWAITING_REPORT','UNREPORTED','AMBIGUOUS','LIKELY_MATCH')`).bind(id).all<Usage>()).results;if(!usages.length)return NextResponse.json({ok:true,updated:0});
  const times=usages.flatMap(row=>row.action_at?[row.action_at]:[]),windowMinutes=Math.max(1,Number(process.env.PERMISSION_MATCH_WINDOW_MINUTES)||10),min=Math.min(...times)-windowMinutes*60,max=Math.max(...times)+windowMinutes*60;
  const reports=(await env.DB.prepare(`SELECT pr.id,pr.public_id,u.discord_id,pr.permission_type,pr.target_player_id,COALESCE(pr.incident_at,pr.created_at) incident_at FROM permission_reports pr JOIN users u ON u.id=pr.created_by_user_id WHERE COALESCE(pr.incident_at,pr.created_at) BETWEEN ? AND ? AND pr.id NOT IN (SELECT matched_permission_report_id FROM permission_usage_logs WHERE matched_permission_report_id IS NOT NULL AND import_batch_id<>?)`).bind(min,max,id).all<Report>()).results;
  const candidates:PermissionReportCandidate[]=reports.flatMap(row=>{const permission=normalizePermission(row.permission_type);return permission?[{id:row.id,publicId:row.public_id,staffDiscordId:row.discord_id,permission,targetPlayerId:row.target_player_id,incidentAt:new Date(row.incident_at*1000)}]:[];});
  const results=reconcilePermissionUsage(usages.map(row=>({id:row.id,sourceRowNumber:row.source_row_number,staffDiscordId:row.staff_discord_id,permission:normalizePermission(row.permission_type),targetPlayerId:row.target_player_id,targetDiscordId:row.target_discord_id,actionAt:row.action_at?new Date(row.action_at*1000):null,rawLogId:row.raw_log_id,validationError:row.validation_error})),candidates,{matchWindowMinutes:windowMinutes,graceMinutes:Number(process.env.PERMISSION_REPORT_GRACE_MINUTES)||15});
  const now=Math.floor(Date.now()/1000),changed=results.filter(result=>result.status!=="UNREPORTED"||result.matchedReportId);const statements=changed.map(result=>env.DB.prepare(`UPDATE permission_usage_logs SET match_status=?,matched_permission_report_id=?,time_difference_seconds=?,match_explanation_json=? WHERE id=?`).bind(result.status,result.matchedReportId,result.timeDifferenceSeconds,JSON.stringify(result.explanation),result.id));statements.push(env.DB.prepare(`INSERT INTO audit_logs (id,actor_user_id,action,new_value,created_at) VALUES (?,?,?,?,?)`).bind(crypto.randomUUID(),access.user.id,"PERMISSION_USAGE_MATCHED",JSON.stringify({importBatchId:id,rechecked:results.length,updated:changed.length}),now));for(let i=0;i<statements.length;i+=50)await env.DB.batch(statements.slice(i,i+50));return NextResponse.json({ok:true,rechecked:results.length,updated:changed.length});
}
