import { env } from "cloudflare:workers";
import { NextRequest, NextResponse } from "next/server";
import { normalizePermission, reconcilePermissionUsage } from "../../../../../lib/reconciliation";
import { requireHigherStaffManagement } from "../../../../../lib/server-auth";

type UsageRow={id:string;source_row_number:number;staff_discord_id:string|null;permission_type:string|null;target_player_id:string|null;target_discord_id:string|null;action_at:number|null;raw_log_id:string|null;validation_error:string|null};
type ReportRow={id:number;public_id:string;discord_id:string;permission_type:string;target_player_id:string;incident_at:number};
const auditAction:Record<string,string>={link:"PERMISSION_USAGE_MANUALLY_LINKED",duplicate:"PERMISSION_USAGE_MARKED_DUPLICATE",exception:"PERMISSION_USAGE_MARKED_EXCEPTION",keep_unreported:"PERMISSION_USAGE_MARKED_UNREPORTED",rerun:"PERMISSION_USAGE_MATCHED"};

export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){
  const access=await requireHigherStaffManagement();if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const {id}=await params;
  const body=await request.json().catch(()=>null) as {action?:string;reportId?:number;reason?:string}|null;if(!body?.action||!auditAction[body.action])return NextResponse.json({error:"Unsupported reconciliation action."},{status:400});
  const usage=await env.DB.prepare(`SELECT id,source_row_number,staff_discord_id,permission_type,target_player_id,target_discord_id,action_at,raw_log_id,validation_error FROM permission_usage_logs WHERE id=?`).bind(id).first<UsageRow>();if(!usage)return NextResponse.json({error:"Permission usage not found."},{status:404});
  const now=Math.floor(Date.now()/1000);let status="UNREPORTED",matchedReportId:number|null=null,timeDifference:number|null=null,explanation:Record<string,unknown>={confidence:"Confirmed unreported by Higher Staff"};
  if(body.action==="link"){
    if(!body.reportId)return NextResponse.json({error:"Select a Permission Report to link."},{status:400});const report=await env.DB.prepare(`SELECT pr.id,pr.public_id,u.discord_id,pr.permission_type,pr.target_player_id,COALESCE(pr.incident_at,pr.created_at) incident_at FROM permission_reports pr JOIN users u ON u.id=pr.created_by_user_id WHERE pr.id=?`).bind(body.reportId).first<ReportRow>();if(!report)return NextResponse.json({error:"Permission Report not found."},{status:404});status="MANUALLY_RESOLVED";matchedReportId=report.id;timeDifference=usage.action_at?Math.round(Math.abs(report.incident_at-usage.action_at)):null;explanation={confidence:"Manually linked by Higher Staff",staffDiscordId:report.discord_id===usage.staff_discord_id?"Exact":"Different",permission:report.permission_type===usage.permission_type?"Exact":"Different",targetPlayerId:report.target_player_id===usage.target_player_id?"Exact":"Different",timeDifferenceSeconds:timeDifference};
  }else if(body.action==="duplicate")status="DUPLICATE";else if(body.action==="exception"){if(!body.reason?.trim())return NextResponse.json({error:"An exception reason is required."},{status:400});status="EXCEPTION";}else if(body.action==="rerun"){
    const windowMinutes=Math.max(1,Number(process.env.PERMISSION_MATCH_WINDOW_MINUTES)||10);const actionAt=usage.action_at?new Date(usage.action_at*1000):null;const rows=actionAt?(await env.DB.prepare(`SELECT pr.id,pr.public_id,u.discord_id,pr.permission_type,pr.target_player_id,COALESCE(pr.incident_at,pr.created_at) incident_at FROM permission_reports pr JOIN users u ON u.id=pr.created_by_user_id WHERE u.discord_id=? AND pr.permission_type=? AND pr.target_player_id=? AND COALESCE(pr.incident_at,pr.created_at) BETWEEN ? AND ? AND pr.id NOT IN (SELECT matched_permission_report_id FROM permission_usage_logs WHERE matched_permission_report_id IS NOT NULL AND id<>?)`).bind(usage.staff_discord_id,usage.permission_type,usage.target_player_id,usage.action_at!-windowMinutes*60,usage.action_at!+windowMinutes*60,id).all<ReportRow>()).results:[];
    const result=reconcilePermissionUsage([{id:usage.id,sourceRowNumber:usage.source_row_number,staffDiscordId:usage.staff_discord_id,permission:normalizePermission(usage.permission_type),targetPlayerId:usage.target_player_id,targetDiscordId:usage.target_discord_id,actionAt,rawLogId:usage.raw_log_id,validationError:usage.validation_error}],rows.map(row=>({id:row.id,publicId:row.public_id,staffDiscordId:row.discord_id,permission:normalizePermission(row.permission_type)!,targetPlayerId:row.target_player_id,incidentAt:new Date(row.incident_at*1000)})),{matchWindowMinutes:windowMinutes,graceMinutes:Number(process.env.PERMISSION_REPORT_GRACE_MINUTES)||15});status=result[0].status;matchedReportId=result[0].matchedReportId;timeDifference=result[0].timeDifferenceSeconds;explanation=result[0].explanation;
  }
  await env.DB.batch([env.DB.prepare(`UPDATE permission_usage_logs SET match_status=?,matched_permission_report_id=?,time_difference_seconds=?,match_explanation_json=?,review_status='Reviewed',reviewed_by_user_id=?,reviewed_at=?,review_note=? WHERE id=?`).bind(status,matchedReportId,timeDifference,JSON.stringify(explanation),access.user.id,now,body.reason?.trim()||null,id),env.DB.prepare(`INSERT INTO audit_logs (id,actor_user_id,action,new_value,created_at) VALUES (?,?,?,?,?)`).bind(crypto.randomUUID(),access.user.id,auditAction[body.action],JSON.stringify({usageId:id,status,matchedReportId,note:body.reason?.trim()||null}),now)]);
  return NextResponse.json({ok:true,status,matchedReportId,timeDifferenceSeconds:timeDifference,explanation});
}
