import { env } from "cloudflare:workers";
import { NextRequest, NextResponse } from "next/server";
import { normalizePermission, reconcilePermissionUsage } from "../../../lib/reconciliation";
import { requireStaffSession } from "../../../lib/server-auth";

type Usage={id:string;source_row_number:number;staff_discord_id:string|null;permission_type:string|null;target_player_id:string|null;target_discord_id:string|null;action_at:number|null;raw_log_id:string|null;validation_error:string|null};
const allowedMime=new Set(["image/png","image/jpeg","image/webp","video/mp4","video/webm"]);

export async function POST(request:NextRequest){
  const access=await requireStaffSession();if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});const form=await request.formData();
  const permission=normalizePermission(form.get("permission")),targetPlayerId=String(form.get("targetPlayerId")??"").trim(),targetPlayerName=String(form.get("targetPlayerName")??"").trim()||null,targetDiscordId=String(form.get("targetDiscordId")??"").trim()||null,reason=String(form.get("reason")??"").trim(),incidentRaw=String(form.get("incidentAt")??"");
  const incidentAt=new Date(incidentRaw);if(!permission)return NextResponse.json({error:"Select one of the nine supported permissions."},{status:400});if(!targetPlayerId)return NextResponse.json({error:"Target Player ID is required."},{status:400});if(reason.length<20)return NextResponse.json({error:"Provide a meaningful reason of at least 20 characters."},{status:400});if(Number.isNaN(incidentAt.getTime()))return NextResponse.json({error:"Choose a valid incident date and time."},{status:400});
  const files=form.getAll("evidence").filter((item):item is File=>item instanceof File&&item.size>0),url=String(form.get("evidenceUrl")??"").trim();const maxMb=Math.max(1,Number(process.env.MAX_UPLOAD_SIZE_MB)||100);
  for(const file of files){if(!allowedMime.has(file.type))return NextResponse.json({error:`Unsupported evidence type: ${file.name}`},{status:415});if(file.size>maxMb*1024*1024)return NextResponse.json({error:`${file.name} exceeds the ${maxMb} MB limit.`},{status:413});}
  if(url){try{const parsed=new URL(url);if(parsed.protocol!=="https:")throw new Error();}catch{return NextResponse.json({error:"Evidence URL must be a valid HTTPS address."},{status:400});}}
  const publicId=`ER-PR-${String(Date.now()).slice(-7)}`,now=Math.floor(Date.now()/1000),noEvidence=files.length===0&&!url;
  await env.DB.prepare(`INSERT INTO permission_reports (public_id,created_by_user_id,permission_type,target_player_name,target_player_id,target_discord_id,reason,incident_at,status,no_evidence,priority,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(publicId,access.user.id,permission,targetPlayerName,targetPlayerId,targetDiscordId,reason,Math.floor(incidentAt.getTime()/1000),"Pending",noEvidence?1:0,noEvidence?"High":"Normal",now,now).run();
  const report=await env.DB.prepare(`SELECT id FROM permission_reports WHERE public_id=?`).bind(publicId).first<{id:number}>();if(!report)throw new Error("Permission Report could not be created.");const statements:D1PreparedStatement[]=[];
  for(const file of files){const evidenceId=crypto.randomUUID(),key=`evidence/${publicId}/${evidenceId}`;await env.EVIDENCE!.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type},customMetadata:{filename:file.name,reportId:String(report.id)}});statements.push(env.DB.prepare(`INSERT INTO evidence (id,report_id,kind,object_key,file_name,mime_type,size_bytes,uploaded_by_user_id,created_at) VALUES (?,?,?,?,?,?,?,?,?)`).bind(evidenceId,report.id,file.type.startsWith("image/")?"Image":"Video",key,file.name,file.type,file.size,access.user.id,now));}
  if(url)statements.push(env.DB.prepare(`INSERT INTO evidence (id,report_id,kind,external_url,uploaded_by_user_id,created_at) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),report.id,"External URL",url,access.user.id,now));statements.push(env.DB.prepare(`INSERT INTO audit_logs (id,report_id,actor_user_id,action,new_value,created_at) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),report.id,access.user.id,"PERMISSION_REPORT_CREATED",JSON.stringify({publicId,permission,targetPlayerId,noEvidence}),now));if(statements.length)await env.DB.batch(statements);
  const windowMinutes=Math.max(1,Number(process.env.PERMISSION_MATCH_WINDOW_MINUTES)||10),center=Math.floor(incidentAt.getTime()/1000);const usages=(await env.DB.prepare(`SELECT id,source_row_number,staff_discord_id,permission_type,target_player_id,target_discord_id,action_at,raw_log_id,validation_error FROM permission_usage_logs WHERE staff_discord_id=? AND permission_type=? AND target_player_id=? AND action_at BETWEEN ? AND ? AND match_status IN ('AWAITING_REPORT','UNREPORTED','AMBIGUOUS') ORDER BY ABS(action_at-?) LIMIT 10`).bind(access.user.discordId,permission,targetPlayerId,center-windowMinutes*60,center+windowMinutes*60,center).all<Usage>()).results;
  if(usages.length){const results=reconcilePermissionUsage(usages.map(row=>({id:row.id,sourceRowNumber:row.source_row_number,staffDiscordId:row.staff_discord_id,permission:normalizePermission(row.permission_type),targetPlayerId:row.target_player_id,targetDiscordId:row.target_discord_id,actionAt:row.action_at?new Date(row.action_at*1000):null,rawLogId:row.raw_log_id,validationError:row.validation_error})),[{id:report.id,publicId,staffDiscordId:access.user.discordId,permission,targetPlayerId,incidentAt}],{matchWindowMinutes:windowMinutes,graceMinutes:Number(process.env.PERMISSION_REPORT_GRACE_MINUTES)||15});const matched=results.find(result=>result.matchedReportId===report.id);if(matched)await env.DB.batch([env.DB.prepare(`UPDATE permission_usage_logs SET match_status=?,matched_permission_report_id=?,time_difference_seconds=?,match_explanation_json=? WHERE id=?`).bind(matched.status,report.id,matched.timeDifferenceSeconds,JSON.stringify(matched.explanation),matched.id),env.DB.prepare(`INSERT INTO audit_logs (id,report_id,actor_user_id,action,new_value,created_at) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),report.id,access.user.id,"PERMISSION_USAGE_MATCHED",JSON.stringify({usageId:matched.id,source:"new_permission_report"}),now)]);}
  return NextResponse.json({ok:true,publicId,reportId:report.id,noEvidence});
}
