import { env } from "../../../../lib/platform-env";
import { NextRequest, NextResponse } from "next/server";
import { requireHigherStaffManagement } from "../../../../lib/server-auth";

export async function GET(request:NextRequest){
  const access=await requireHigherStaffManagement();if(!access.ok)return NextResponse.json({error:access.error},{status:access.status});
  if(process.env.LOCAL_DEMO_MODE==="true"&&process.env.NODE_ENV!=="production")return NextResponse.json({stats:{total:0,matched:0,likely:0,unreported:0,awaiting:0,ambiguous:0,invalid:0,duplicates:0},usages:[],imports:[],coverage:[]});
  const batch=new URL(request.url).searchParams.get("batch");const where=batch?"WHERE plu.import_batch_id=?":"";const usageQuery=env.DB.prepare(`SELECT plu.id,plu.match_status,plu.staff_discord_id,COALESCE(u.display_name,'Unknown Staff Discord ID') staff_name,COALESCE(u.staff_rank,'Unknown') staff_rank,plu.permission_type,plu.target_player_id,plu.action_at,pr.public_id matched_report,plu.time_difference_seconds,plu.review_status,pli.public_id import_public_id FROM permission_usage_logs plu JOIN permission_log_imports pli ON pli.id=plu.import_batch_id LEFT JOIN users u ON u.id=plu.staff_user_id LEFT JOIN permission_reports pr ON pr.id=plu.matched_permission_report_id ${where} ORDER BY plu.action_at DESC LIMIT 500`);const usageRows=batch?(await usageQuery.bind(batch).all()).results:(await usageQuery.all()).results;
  const history=(await env.DB.prepare(`SELECT pli.id,pli.public_id,pli.filename,pli.file_type,pli.file_size,pli.total_rows,pli.matched_rows,pli.unmatched_rows,pli.invalid_rows,pli.duplicate_rows,pli.status,pli.created_at,u.display_name uploaded_by FROM permission_log_imports pli LEFT JOIN users u ON u.id=pli.uploaded_by_user_id ORDER BY pli.created_at DESC LIMIT 100`).all()).results;
  const coverage=(await env.DB.prepare(`SELECT COALESCE(u.display_name,'Unknown Staff Discord ID') staff_name,COALESCE(u.staff_rank,'Unknown') staff_rank,plu.staff_discord_id,COUNT(*) detected,SUM(CASE WHEN plu.match_status IN ('MATCHED','LIKELY_MATCH','MANUALLY_RESOLVED') THEN 1 ELSE 0 END) matched,SUM(CASE WHEN plu.match_status='UNREPORTED' THEN 1 ELSE 0 END) unreported FROM permission_usage_logs plu LEFT JOIN users u ON u.id=plu.staff_user_id WHERE plu.match_status NOT IN ('INVALID','DUPLICATE') GROUP BY plu.staff_discord_id,u.display_name,u.staff_rank ORDER BY detected DESC LIMIT 100`).all()).results;
  const stats=await env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN match_status='MATCHED' THEN 1 ELSE 0 END) matched,SUM(CASE WHEN match_status='LIKELY_MATCH' THEN 1 ELSE 0 END) likely,SUM(CASE WHEN match_status='UNREPORTED' THEN 1 ELSE 0 END) unreported,SUM(CASE WHEN match_status='AWAITING_REPORT' THEN 1 ELSE 0 END) awaiting,SUM(CASE WHEN match_status='AMBIGUOUS' THEN 1 ELSE 0 END) ambiguous,SUM(CASE WHEN match_status='INVALID' THEN 1 ELSE 0 END) invalid,SUM(CASE WHEN match_status='DUPLICATE' THEN 1 ELSE 0 END) duplicates FROM permission_usage_logs`).first();
  return NextResponse.json({stats,usages:usageRows,imports:history,coverage});
}
